<!DOCTYPE html>
<html lang="en">
<?php include (__DIR__ . '/../base/head.phtml') ?>
<body class="body bg poppins-medium">
    <?php include (__DIR__ . '/../base/header.phtml') ?>
    <main class="wrapper main">
        <div class="window">
            <div class="form">
                <p class="form__title archivo-black-regular">NEW MATCH</p>
                <form class="form__container" action="/new-match" method="POST">
                    <div class="form__container-part">
                        <div class="form__container-input">
                            <label class="form__label" for="p1name">Player Name 1</label>
                            <input class="form__input"
                                   type="text" id="p1name"
                                   name="playerName1"
                                   placeholder="Daniil Medvedev"
                                   value="<?= htmlspecialchars($playerName1 ?? '') ?>">
                        </div>
                        <?php if (isset($errors['playerName1'])): ?>
                            <ul class="list error-list">
                                <?php  foreach ($errors['playerName1'] as $errorMessage): ?>
                                    <li><?= $errorMessage ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif ?>
                    </div>
                    <div class="form__container-part">
                        <div class="form__container-input">
                            <label class="form__label" for="p2name">Player Name 2</label>
                            <input class="form__input"
                                   type="text"
                                   id="p2name"
                                   name="playerName2"
                                   placeholder="Jean-Julien Rojer"
                                   value="<?= htmlspecialchars($playerName2 ?? '') ?>">
                        </div>
                        <?php if (isset($errors['playerName2'])): ?>
                            <ul class="list error-list">
                                <?php  foreach ($errors['playerName2'] as $errorMessage): ?>
                                    <li><?= $errorMessage ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif ?>
                    </div>
                    <input class="button form__button" type="submit" value="Start">
                </form>
            </div>
        </div>
    </main>
    <?php include (__DIR__ .'/../base/footer.phtml') ?>
</body>
</html>