<!DOCTYPE html>
<html lang="en">
<?php include(__DIR__ . '/html/base/head.phtml') ?>
<body class="body bg poppins-medium">
    <?php include (__DIR__ . '/html/base/header.phtml') ?>
    <main class="wrapper main">
            <div class="window">
                <div class="window__content">
                    <img class="image" src="assets/images/scoreboard-logo.png" alt="scoreboard logo">
                    <div class="window__buttons">
                        <a class="button" href="/new-match">New Match</a>
                        <a class="button" href="/matches">Matches</a>
                    </div>
                </div>
            </div>
    </main>
    <?php include (__DIR__ . '/html/base/footer.phtml') ?>
</body>
</html>